### ISSUE TITLE
Makefile broken?

### ISSUE THREAD

**Issue by ghost** [icyleaf/fast-crystal#2]
after running make I get 

```bash
 ~/Desktop/fast-crystal[master]> make

/usr/local/bin/crystal build --release -o bin/fast-crystal src/fast-crystal.cr 
ld: can't open output file for writing: ~/Desktop/fast-crystal/bin/fast-crystal, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '~/Desktop/fast-crystal/bin/fast-crystal'  -rdynamic  -lpcre -lgc -lpthread /usr/local/Cellar/crystal-lang/0.23.1_1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`
make: *** [build] Error 1
```

macOS 10.13, Crystal 0.23.1 (2017-09-08) LLVM 4.0.1, GNU Make 3.81

**Comment by straight-shoota** [comment]
Looks like crystal-lang/crystal#4719 
So it's an issue of the Crystal compiler, not the makefile. A workaround is to just add `--no-debug` to the compiler command.

**Comment by straight-shoota** [comment]
I guess it needs to create `bin` directory.

**Comment by ghost** [comment]
yes wondered why `clean` has `mkdir bin` at the end anyway

do you know if there are plans/ feasible solutions such as to address reverse.each being converted to reverse_each e.g.?

**Comment by icyleaf** [comment]
Change it `Makefile`,  now it works.
