### ISSUE TITLE
explain why

### ISSUE THREAD

**Issue by pynixwang** [icyleaf/fast-crystal#7]
eg.

`first` does not check bounds
and
`[]` always checks

**Comment by icyleaf** [comment]
What do you mean?

**Comment by pynixwang** [comment]
@icyleaf 

explain why `fast` is faster than `slow`

**Comment by pynixwang** [comment]
try to find the rabbit in the hole.

**Comment by icyleaf** [comment]
Here was the result with no explain, you can read the source code to know it. sorry pal.
